// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yloaperhotkzoyjihhyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlsb2FwZXJob3Rrem95amloaHl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNzkyMzIsImV4cCI6MjA2MjY1NTIzMn0.k5_6EGG0ptX4wudGdKu-tVS3f_ocil5Ph-JiqSMVGec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);